{% set name = "griffe" %}
{% set version = "0.48.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/griffe-{{ version }}.tar.gz
  sha256: f099461c02f016b6be4af386d5aa92b01fb4efe6c1c2c360dda9a5d0a863bb7f

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 3
  noarch: python
  entry_points:
    - griffe = griffe:main

requirements:
  host:
    - python >=3.8
    - pdm >2
    - pdm-backend
    - pip
  run:
    - python >=3.8
    - astunparse >=1.6
    - colorama >=0.4
    - backports.strenum >=1.3

test:
  imports:
    - griffe
  commands:
    - griffe --help
    - griffe --version
    - pip check
  requires:
    - pip

about:
  home: https://mkdocstrings.github.io/griffe
  doc_url: https://mkdocstrings.github.io/griffe
  dev_url: https://github.com/mkdocstrings/griffe
  summary: Signatures for entire Python programs. Extract the structure, the frame, the skeleton of your project, to generate API documentation or find breaking changes in your API.
  license: ISC
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bandersen23
    - dbast
