{% set name = "griffe" %}
{% set version = "0.22.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/griffe-{{ version }}.tar.gz
  sha256: a3c25a2b7bf729ecee7cd455b4eff548f01c620b8f58a8097a800caad221f12e

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  noarch: python
  entry_points:
    - griffe = griffe.cli:main

requirements:
  host:
    - pip <22
    - python >=3.7
    - pdm
  run:
    - python >=3.7
    - cached-property

test:
  imports:
    - griffe
    - griffe.loader
    - griffe.docstrings.parsers
    - griffe.dataclasses
  commands:
    - griffe -h
    - griffe griffe
    - pip check
  requires:
    - pip

about:
  home: https://mkdocstrings.github.io/griffe
  doc_url: https://mkdocstrings.github.io/griffe
  dev_url: https://github.com/mkdocstrings/griffe
  summary: Signatures for entire Python programs. Extract the structure, the frame, the skeleton of your project, to generate API documentation or find breaking changes in your API.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bandersen23
