{% set name = "griffe" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/griffe-{{ version }}.tar.gz
  sha256: 0b4658443858465c13b2de07ff5e15a1032bc889cfafad738a476b8b97bb28d7

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python
  entry_points:
    - griffe = griffe:main

requirements:
  host:
    - python {{ python_min }}
    - pdm >2
    - pdm-backend
    - pip
  run:
    - python >={{ python_min }}
    - colorama >=0.4

test:
  imports:
    - griffe
  commands:
    - griffe --help
    - griffe --version
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://mkdocstrings.github.io/griffe
  doc_url: https://mkdocstrings.github.io/griffe
  dev_url: https://github.com/mkdocstrings/griffe
  summary: Signatures for entire Python programs. Extract the structure, the frame, the skeleton of your project, to generate API documentation or find breaking changes in your API.
  license: ISC
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bandersen23
    - dbast
