{% set name = "griffe" %}
{% set version = "0.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/griffe-{{ version }}.tar.gz
  sha256: a445b3f64662d29584f1691e5d5573ed64d6ee7a1cac86be7d6807b1ac0c51e5

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  host:
    - pip
    - python
    - pdm
  run:
    - python
    - cached_property 

test:
  source_files:
    - tests
  imports:
    - griffe
  commands:
    - pip check
    - pytest
  requires:
    - pip
    - pytest >=6.2
    - pytest-xdist >=2.4

about:
  home: https://mkdocstrings.github.io/griffe
  doc_url: https://mkdocstrings.github.io/griffe
  dev_url: https://github.com/mkdocstrings/griffe
  summary: Signatures for entire Python programs. Extract the structure, the frame, the skeleton of your project, to generate API documentation or find breaking changes in your API.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bandersen23
